### ISSUE TITLE
Project name looks broken in readme 

### ISSUE THREAD

**Issue by forki** [msr-quarc/Liquid#3] opened 2015-11-07 08:20 UTC
I assume the file encoding is broken

**Comment by dbwz8** [comment] 2015-11-07 22:53
Actually, it renders correctly in MarkDown. The problem is that we're using a mathematical font, so the final characters are U (unitary matrix) I (sqrt -1) |> (ket symbol for a column vector). Trust me, not the easiest thing to edit <g>. Note that it all looks fine when rendered on GitHub <g>

**Comment by martincostello** [comment] 2015-11-11 20:46
Looks odd to me as well. I assume there's a font I have missing, but I'm not sure which one it is.

**Comment by dbwz8** [comment] 2015-11-12 03:21
It should look fine on the web site. If you edit it with a text editor it won't work because it's from an extended Unicode character set (that MarkDown knows how to render in a browser).

**Comment by forki** [comment] 2015-11-12 06:59
Thing is it doesn't look good. That's why I reported it.

**Comment by martincostello** [comment] 2015-11-12 08:22
I'm looking at in GitHub.com in Chrome, and I just get Unicode placeholder boxes. On iOS Safari they're just missing.

**Comment by dbwz8** [comment] 2015-11-12 15:29
Mea Culpa. I thought you were talking about in a text editor. I'll check it across browsers and come up with a way to get it to render well. THANKS!

**Comment by dbwz8** [comment] 2015-11-12 16:33
I've tried using straight HTML escape codes for the acronym. It kind of goes against the spirit of Markdown, but at least it might work ;). It renders for me correctly across all browsers... but so did the old one (you're probably missing a math font). I won't close this until I hear back how it renders for you now. I can always go to an image or MathJax if necessary.

**Comment by martincostello** [comment] 2015-11-12 17:23
Still looks odd to me on iOS Safari. Will see what it looks like in Chrome when I'm at a proper computer.

**Comment by dbwz8** [comment] 2015-11-12 22:09
iOS was a good indicator. It also wasn't rendering right on WindowsPhone... so now that's working correctly. Let me know if there are still problems on any platforms. We really only have the one Unicode character at the end (the \ket). I can switch that out as well if necessary.

**Comment by martincostello** [comment] 2015-11-12 22:43
LGTM now on Chrome, Edge and Firefox on Windows 10 and in iOS Safari 9 :+1:

**Comment by dbwz8** [comment] 2015-11-13 04:50
AFAICT we're good to go. Thanks to everyone for catching this.

**Closed by dbwz8** 2015-11-13 04:50 UTC
